# COAT + ai-toolkit 服装FLUX LoRA训练配置
# 使用COAT的FP8优化实现无损加速

job: extension
config:
  # 任务名称
  name: "flux_lora_clothing_coat"
  
  # COAT配置 (自定义扩展)
  coat:
    # 启用COAT优化
    enabled: true
    
    # FP8优化器配置
    optimizer:
      use_fp8: true
      m1_format: "e4m3"  # 一阶动量格式
      m2_format: "e4m3"  # 二阶动量格式  
      block_size: 128
      use_dynamic_range_expansion: true
    
    # FP8激活配置
    activation:
      use_fp8: true
      linear_granularity: "per_tensor"      # 线性层使用per-tensor量化
      nonlinear_granularity: "per_group"    # 非线性层使用per-group量化
      group_size: 128
    
    # 内存优化 (8GB显存增强版)
    memory:
      enable_efficient_checkpoint: true
      log_memory_stats: true
      gradient_checkpointing: true  # 启用梯度检查点
      cpu_offload: false  # CPU卸载会更慢，先不启用
  
  # 训练配置
  process:
    - type: "sd_trainer"
      training_folder: "output/flux_lora_clothing_coat"
      
      # 设备配置
      device: cuda:0
      
      # FLUX模型配置
      network:
        type: "lora"
        linear: 16        # LoRA rank
        linear_alpha: 16
        
        # 可选: 只训练特定层
        # network_kwargs:
        #   only_if_contains:
        #     - "transformer.single_transformer_blocks.7.proj_out"
        #     - "transformer.single_transformer_blocks.20.proj_out"
      
      # 保存配置
      save:
        dtype: bf16
        save_every: 500
        max_step_saves_to_keep: 3
      
      # 数据集配置
      datasets:
        - folder_path: "datasets/clothing"  # 服装图片文件夹
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [512]  # 8GB显存: 只使用512分辨率
          
      # 训练参数
      train:
        batch_size: 1
        steps: 5000
        gradient_accumulation_steps: 8  # 增加梯度累积以弥补小batch size
        
        # 学习率
        lr: 1e-4
        
        # 使用COAT FP8优化器
        optimizer: "coat_fp8_adamw"  # 自定义优化器类型
        
        # 梯度裁剪
        gradient_clipping: 1.0
        
        # 噪声调度
        noise_scheduler: "flowmatch"  # FLUX使用flowmatch
        
        # EMA
        ema_config:
          use_ema: true
          ema_decay: 0.999
        
        # 混合精度
        dtype: bf16  # COAT在bf16基础上使用FP8
      
      # 模型配置
      model:
        name_or_path: "C:\\Users\\14155\\Desktop\\flux lora\\models\\AI-ModelScope\\FLUX___1-dev"
        is_flux: true
        quantize: false  # COAT有自己的量化方案
      
      # 采样配置
      sample:
        sampler: "flowmatch"
        sample_every: 500
        width: 512
        height: 512
        prompts:
          # 基于真实训练数据的测试 prompt
          - "front view, whole body, a model wearing a deep grey t-shirt with round neckline and short sleeves, black wide-leg pants, black chunky shoes, standing against plain white background, fashion photography"
          - "a 23 year old European female model wearing [trigger] style grey t-shirt and black pants, natural orange-brown long wavy hair, fashion photography, high quality"
          - "a model wearing [trigger] black wide-leg pants and chunky shoes, fashionable style, studio lighting"
          - "close up of [trigger] deep grey t-shirt, round neckline, fabric texture, detailed"
        neg: "blurry, low quality, distorted, deformed"
        seed: 42
        walk_seed: true
        guidance_scale: 3.5
        sample_steps: 28
      
      # 触发词
      trigger_word: "sks"
      
      # 日志
      logging:
        log_every: 10
        use_wandb: false  # 可选: 使用Weights & Biases



